import os,subprocess,sys
DOCS="docs"
F={}
F["WORKFLOW_PROTECTION_STANDARD.md"]="# Workflow Protection Standard\nStatus: APPROVED\n\n## Invariants\n- INV-001: Level 0->1 requires REASONED evidence (F-011 gate)\n- INV-002: BLOCK prevents all transitions\n- INV-003: WARN allows transition, surfaced to user\n- INV-004: Gap status forward-only OPEN->PARTIAL->RESOLVED\n- INV-005: Every iteration produces audit log\n- INV-006: assess/integrate/evaluate chain is atomic\n- INV-007: Domain detection is stateless\n- INV-008: Schema validation before state update\n- INV-009: Read-only endpoints never mutate state\n- INV-010: Production path import firewall\n\n## Parity Suite\n- Runner: PYTHONPATH=. python3 scripts/run_replay_benchmark_v2.py\n- Excluded: TC-12 TC-16 (DR-006 QUARANTINED)\n- Pass threshold: 23/23\n\n## Rollback\n1. git revert HEAD\n2. Run F-011 gate\n3. Run parity suite\n4. File finding document\n"
F["DISASTER_RECOVERY_PLAN.md"]="# Disaster Recovery Plan\nStatus: APPROVED\n\n## Scenario 1 - Codespace Reset\nRTO: 30min | RPO: Last commit\n1. Reopen Codespace\n2. git log --oneline -5\n3. Run F-011 gate\n4. Re-generate lost untracked files\nPrevention: Commit benchmark/results_20260520_074904.json (R-004)\n\n## Scenario 2 - Claude API Unavailable\nRTO: 0 (graceful) | RPO: N/A\n1. Web layer catches HTTP errors\n2. Return WARN verdict\n3. No state changes during outage\n\n## Scenario 3 - Broken Main Branch\nRTO: 15min\n1. git revert SHA\n2. Run F-011 gate\n3. Run parity suite\n\n## Scenario 4 - Session Store Corruption\nRTO: Immediate\nSESSION_STORE is ephemeral by design. Restart Flask.\n\n## Scenario 5 - Corrupt Replay Fixture\nRTO: 1 hour\ngit checkout SHA -- tests/replay/cases/TC.json\n\n## Scenario 6 - Deprecated Model F-013\nRTO: 1 day\nDo NOT use v1 benchmark. Use v2 exclusively.\nF-013 requires owner approval.\n"
F["OBSERVABILITY_ARCHITECTURE.md"]="# Observability Architecture\nStatus: APPROVED\n\n## Log Format\n{timestamp_iso} | {level} | {session_id} | {component} | {event} | {payload_json}\n\n## Log Levels\nDEBUG 7 days / INFO-WARN-ERROR 30 days / AUDIT 365 days\n\n## 21 Metrics\nM-01 inv_sessions_total Counter\nM-02 inv_sessions_active Gauge\nM-03 inv_iterations_total Counter\nM-04 inv_verdict_pass_total Counter\nM-05 inv_verdict_warn_total Counter\nM-06 inv_verdict_block_total Counter\nM-07 inv_transition_l0_l1_total Counter\nM-08 inv_transition_l1_l2_total Counter\nM-09 llm_call_latency_ms Histogram\nM-10 llm_call_total Counter\nM-11 llm_call_error_total Counter\nM-12 llm_tokens_input_total Counter\nM-13 llm_tokens_output_total Counter\nM-14 llm_schema_validation_fail_total Counter\nM-15 inv_gap_open_total Counter\nM-16 inv_gap_resolved_total Counter\nM-17 inv_session_duration_s Histogram\nM-18 inv_domain_detection_total Counter\nM-19 web_request_latency_ms Histogram\nM-20 web_request_error_total Counter\nM-21 inv_cost_usd_total Counter\n\n## 20 Audit Events\nAE-01 session.created\nAE-02 session.ended\nAE-03 iteration.started\nAE-04 iteration.completed\nAE-05 verdict.pass\nAE-06 verdict.warn\nAE-07 verdict.block\nAE-08 transition.attempted\nAE-09 transition.approved\nAE-10 transition.denied\nAE-11 gap.opened\nAE-12 gap.partial\nAE-13 gap.resolved\nAE-14 llm.called\nAE-15 llm.responded\nAE-16 llm.error\nAE-17 schema.valid\nAE-18 schema.invalid\nAE-19 domain.detected\nAE-20 cost.recorded\n"
F["SECURITY_ARCHITECTURE.md"]="# Security Architecture\nStatus: APPROVED\n\n## Authentication\nCurrent MVP: Anonymous sessions keyed by UUID4 session_id.\nTarget: Email/password or OAuth. HMAC-SHA256 signed tokens.\n\n## Secrets\n- API keys in .env only\n- .env in .gitignore NEVER commit keys\n- ANTHROPIC_API_KEY rotation: 90 days\n\n## Input Validation\n- Max length 10000 characters\n- Strip null bytes and control characters\n- No HTML rendering of user input\n- All LLM output validated against JSON schema (INV-008)\n- No eval() of LLM output\n\n## Abuse Protection\n- Rate limit: 10 requests/minute per session_id\n- Hard token budget per session\n- User input never interpolated into system prompt\n\n## Pre-Release Checklist\n- [ ] No hardcoded secrets\n- [ ] No eval() or exec() on user or LLM input\n- [ ] HTTPS enforced\n- [ ] .env not committed\n- [ ] DEBUG mode disabled in production\n- [ ] pip audit run no critical CVEs\n"
F["DATA_RETENTION_POLICY.md"]="# Data Retention Policy\nStatus: APPROVED\n\n## Data Inventory\nInvention descriptions: In-memory session store YES sensitive\nClarification responses: In-memory session store YES sensitive\nSession state: In-memory session store YES sensitive\nAudit logs: Log files NO\nBenchmark fixtures: tests/replay/cases/ NO\nBenchmark results: benchmark/ NO\n\n## Retention Schedule\nIn-memory sessions: Until server restart (automatic)\nAudit DEBUG: 7 days\nAudit INFO/WARN/ERROR: 30 days\nAudit AUDIT events: 365 days minimum\nBenchmark fixtures: Indefinite (git controlled)\nBenchmark results: 90 days\n\n## High Priority\nbenchmark/results_20260520_074904.json MUST be committed before Codespace reset (R-004)\n\n## Privacy\n1. Invention descriptions are user IP must not be used for retraining\n2. Anthropic API receives descriptions governed by API ToS\n3. No PII collected in MVP. GDPR/PDPL review required before adding accounts\n"
F["COST_GOVERNANCE_PLAN.md"]="# Cost Governance Plan\nStatus: APPROVED\n\n## Per-Session Budget\nLevel 0: 5 iterations ~1500 tokens = ~7500 tokens\nLevel 1: 5 iterations ~1800 tokens = ~9000 tokens\nLevel 2: 3 iterations ~2000 tokens = ~6000 tokens\nTotal: 13 iterations ~22500 tokens ~0.08-0.12 USD\n\n## Hard Limits\nMax input tokens per call: 4000 (ai_advisor.py)\nMax output tokens per call: 1000 (max_tokens parameter)\nMax iterations per session: 15 (progression_loop.py hard stop)\nMax session cost USD: 0.25 (ai_advisor.py cumulative check)\n\n## Kill Switch\n1. Set INVENTORAI_KILL_SWITCH=1\n2. web/app.py checks on every request\n3. Returns HTTP 503 Service temporarily paused\n4. To re-enable: unset variable and restart\n\n## Monthly Budget\nMVP Internal: 100 sessions ~10 USD\nEarly access: 1000 sessions ~100 USD\nGrowth: 10000 sessions ~1000 USD\n\n## Cost Alerts\nDaily spend >80% of daily budget: Email owner\nSingle session cost >0.20 USD: Log and flag\nMonthly spend >50% by day 15: Email owner\nUnexpected spike 3x average: Immediate email and auto-pause\n"
F["GOVERNANCE_DOCUMENTS.md"]="# Governance Documents - Master Index\nStatus: APPROVED\n\n## Governing Principles\nP-01: Evidence Before Action. No production change without finding or ADR.\nP-02: Regression Gate First. F-011 must pass before any production path commit.\nP-03: Quarantine Do Not Delete. Unverifiable data is QUARANTINED not deleted.\nP-04: Untracked Is Risk. Every session ends with git status review.\nP-05: Scope Freeze Respect. DR-003 MVP Scope Freeze is active.\nP-06: Domain-Agnostic Core. engine/ must remain domain-agnostic.\nP-07: Honest Status. Never claim completion without git commit evidence.\nP-08: Base64 Write Scripts Only. heredoc cat is prohibited.\nP-09: Arabic Safety. Arabic strings must not appear in files processed by eval().\nP-10: Phase Order Enforcement. Phase 6 cannot start until Phase 5 approved.\n\n## Workflow Invariants Reference\nSee WORKFLOW_PROTECTION_STANDARD.md for full definitions.\nINV-001 through INV-010 defined there.\n\n## Domain Registry Contract\nengine/domain_registry.py (Phase 6) must satisfy:\ndomains/<id>/domain.json\ndomains/<id>/system_prompt.md\ndomains/<id>/output_schema.json\nMust produce identical output to hardcoded implementation for 23 non-quarantined fixtures.\n\n## Change Control\nProduction path changes require:\n1. Finding or ADR committed\n2. F-011 gate 10/10 PASS\n3. Parity suite 23/23 PASS\n4. Commit message includes document reference\n\nPhase gates:\nPhase 4 to 5: Governance documents committed (this commit)\nPhase 5 to 6: Migration Plan approved by owner\nPhase 6 to 7: Registry passes 23/23 parity\nPhase 7 to 8: Second domain added and tested\n\n## Document Registry\nWPS-001 docs/WORKFLOW_PROTECTION_STANDARD.md APPROVED\nDRP-001 docs/DISASTER_RECOVERY_PLAN.md APPROVED\nOBS-001 docs/OBSERVABILITY_ARCHITECTURE.md APPROVED\nSEC-001 docs/SECURITY_ARCHITECTURE.md APPROVED\nDRE-001 docs/DATA_RETENTION_POLICY.md APPROVED\nCGP-001 docs/COST_GOVERNANCE_PLAN.md APPROVED\nGOV-001 docs/GOVERNANCE_DOCUMENTS.md APPROVED\n"
os.makedirs(DOCS,exist_ok=True)
os.makedirs("scripts",exist_ok=True)
for fn,content in F.items():
    p=os.path.join(DOCS,fn)
    open(p,"w",encoding="utf-8").write(content)
    lines=content.count("\n")
    print(f"  WRITTEN: {p} ({lines} lines)")
import shutil
shutil.copy("/tmp/wgd.py","scripts/write_governance_docs.py")
print("\nAll 7 documents written.")
